In [2]:
import torch
from einops import rearrange, repeat, einsum, reduce

In [3]:
x = torch.randint(0,10, (6,98,98,3))

In [4]:
x.shape

torch.Size([6, 98, 98, 3])

In [5]:
rearrange(x[0], "h w c -> c h w" ).shape

torch.Size([3, 98, 98])

In [6]:
rearrange(x, "b h w c -> (b h) w c").shape

torch.Size([588, 98, 3])

In [7]:
(x.transpose(1,0).reshape(98, -1, 3) == rearrange(x, "b h w c -> h (b w) c")).all()

tensor(True)

In [8]:
rearrange(x, "b h w c -> (b h w c)").shape

torch.Size([172872])

In [9]:
rearrange(x, "(b1 b2) h w c -> b1 b2 h w c", b2=2).shape

torch.Size([3, 2, 98, 98, 3])

In [10]:
(rearrange(x, "(b1 b2) h w c -> (b1 h) (b2 w) c ", b1=2) == x.reshape(2, -1, 98,98,3).transpose(1,2).reshape(98*2, -1, 3)).all()

tensor(True)

In [11]:
x.reshape(2, -1, 98,98,3).transpose(1,2).reshape(98*2, -1, 3).shape

torch.Size([196, 294, 3])

In [12]:
rearrange(x, "b (h h2) w c -> (h) (b h2 w) c", h2=2).shape

torch.Size([49, 1176, 3])

In [13]:
rearrange(x[0], "A F c -> (A F) c").shape

torch.Size([9604, 3])

In [14]:
x.mean(0, dtype=torch.float).shape

torch.Size([98, 98, 3])

In [15]:
x.shape

torch.Size([6, 98, 98, 3])

In [16]:
res = 0
for i in range(x.shape[0]):
    res += x[i]

In [17]:
res = res / 6

In [18]:
ims = x

In [19]:
ims.shape

torch.Size([6, 98, 98, 3])

In [20]:
# rearrange can also take care of lists of arrays with the same shape
x = list(ims)
print(type(x), "with", len(x), "tensors of shape", x[0].shape)
# that's how we can stack inputs
# "list axis" becomes first ("b" in this case), and we left it there
rearrange(x, "b h w c -> b h w c").shape

<class 'list'> with 6 tensors of shape torch.Size([98, 98, 3])


torch.Size([6, 98, 98, 3])

In [21]:
# but new axis can appear in the other place:
(rearrange(x, "b h w c -> h w c b") == torch.stack(x, dim=-1)).all()

tensor(True)

In [22]:
torch.stack(x, dim=3).shape

torch.Size([98, 98, 3, 6])

In [23]:
y = [torch.randint(0,3,(8, 2,2)) for _ in range(3)]


In [24]:
y[0].shape

torch.Size([8, 2, 2])

In [25]:
y

[tensor([[[2, 0],
          [0, 2]],
 
         [[1, 0],
          [2, 1]],
 
         [[2, 0],
          [2, 0]],
 
         [[0, 0],
          [1, 2]],
 
         [[1, 0],
          [1, 0]],
 
         [[2, 1],
          [0, 2]],
 
         [[0, 0],
          [0, 0]],
 
         [[1, 2],
          [1, 1]]]),
 tensor([[[0, 2],
          [0, 2]],
 
         [[1, 0],
          [1, 0]],
 
         [[1, 1],
          [0, 1]],
 
         [[2, 0],
          [2, 1]],
 
         [[1, 1],
          [0, 0]],
 
         [[1, 0],
          [1, 1]],
 
         [[0, 1],
          [1, 1]],
 
         [[0, 0],
          [1, 2]]]),
 tensor([[[0, 2],
          [1, 1]],
 
         [[1, 1],
          [0, 2]],
 
         [[2, 2],
          [1, 2]],
 
         [[2, 2],
          [0, 2]],
 
         [[0, 0],
          [0, 1]],
 
         [[0, 1],
          [2, 2]],
 
         [[1, 1],
          [0, 2]],
 
         [[0, 2],
          [1, 2]]])]

In [26]:
y = torch.randn((5,5))
y

tensor([[-1.0244,  2.8024,  0.7179,  0.4097,  0.1952],
        [ 0.3038, -1.0218,  1.4613, -0.9497,  0.1175],
        [ 0.0046,  0.0176,  0.0361, -0.1730,  0.7450],
        [-0.3747,  0.2130,  0.2043, -0.3837, -1.5065],
        [-0.7292, -0.2612, -0.6225,  1.4176, -0.1225]])

In [35]:
torch.diag_embed(y[0])

tensor([[-1.0244,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  2.8024,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.7179,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.4097,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.1952]])

In [34]:
einsum(y, "i i-> i").shape

torch.Size([5])

In [50]:
a = torch.randint(1,10,(2,))
b = torch.randint(1,10,(5,))
a

tensor([4, 4])

In [58]:
c = torch.tensor(3)
c.shape

torch.Size([])

In [56]:
b.shape

torch.Size([5])

In [ ]:
torch.einsum()

In [62]:
x = torch.randn(1,10)
W = torch.randn(5,10)

In [68]:
(x @ W.T).shape

torch.Size([1, 5])

In [69]:
(W @ x.squeeze(0)).shape

torch.Size([5])

In [61]:
x.shape

torch.Size([1, 10])

In [53]:
einsum(a, b, "i, j -> i j")

tensor([[16,  8, 12,  8, 16],
        [16,  8, 12,  8, 16]])

In [52]:
torch.outer(a,b)

tensor([[16,  8, 12,  8, 16],
        [16,  8, 12,  8, 16]])

In [27]:
rearrange(y, "i j -> i j")

tensor([[-1.0244,  2.8024,  0.7179,  0.4097,  0.1952],
        [ 0.3038, -1.0218,  1.4613, -0.9497,  0.1175],
        [ 0.0046,  0.0176,  0.0361, -0.1730,  0.7450],
        [-0.3747,  0.2130,  0.2043, -0.3837, -1.5065],
        [-0.7292, -0.2612, -0.6225,  1.4176, -0.1225]])

In [75]:
y[0]

tensor([[[2, 2],
         [0, 0]],

        [[1, 2],
         [2, 1]],

        [[1, 2],
         [1, 1]],

        [[2, 0],
         [1, 1]],

        [[0, 0],
         [0, 2]],

        [[2, 2],
         [0, 0]],

        [[0, 1],
         [2, 2]],

        [[2, 2],
         [2, 1]]])

In [74]:
rearrange(y, "b (d1 d2 c) h w -> b (d2 d1 c) h w", d1=2, d2=2)[0]

tensor([[[2, 2],
         [0, 0]],

        [[1, 2],
         [2, 1]],

        [[0, 0],
         [0, 2]],

        [[2, 2],
         [0, 0]],

        [[1, 2],
         [1, 1]],

        [[2, 0],
         [1, 1]],

        [[0, 1],
         [2, 2]],

        [[2, 2],
         [2, 1]]])

In [64]:
rearrange(y, "b h w c -> (h b) w c")

tensor([[[0, 0, 1],
         [2, 2, 1]],

        [[1, 1, 2],
         [1, 0, 1]],

        [[1, 2, 2],
         [2, 1, 1]],

        [[0, 1, 1],
         [0, 1, 0]],

        [[2, 0, 0],
         [2, 2, 0]],

        [[2, 1, 1],
         [0, 2, 1]]])

In [ ]:
x = rearrange(ims, "b h w c -> b () h w () c")  # functionality of numpy.expand_dims
print(x.shape)
print(rearrange(x, "b 1 h w 1 c -> b h w c").shape)  # functionality of numpy.squeeze

torch.Size([6, 1, 98, 98, 1, 3])
torch.Size([6, 98, 98, 3])


In [ ]:
ims = torch.randint(0,10,(2,2,3,3))

In [ ]:
ims.max(-2).values.max(-2).values

tensor([[8, 8, 8],
        [8, 5, 6]])

In [ ]:
ims

tensor([[[[8, 4, 3],
          [7, 8, 0],
          [5, 4, 1]],

         [[1, 4, 8],
          [1, 0, 7],
          [1, 4, 2]]],


        [[[6, 5, 2],
          [0, 2, 3],
          [6, 2, 0]],

         [[8, 2, 0],
          [0, 4, 0],
          [2, 3, 6]]]])

In [ ]:
repeat(ims[0], "h w c -> h (w 2) c")

tensor([[[8, 4, 3],
         [8, 4, 3],
         [7, 8, 0],
         [7, 8, 0],
         [5, 4, 1],
         [5, 4, 1]],

        [[1, 4, 8],
         [1, 4, 8],
         [1, 0, 7],
         [1, 0, 7],
         [1, 4, 2],
         [1, 4, 2]]])

In [ ]:
reduce(ims, "b h w c -> b () () c", "max")

tensor([[[[8, 5, 6]]],


        [[[9, 8, 8]]],


        [[[8, 8, 8]]]])

In [ ]:
ims = x
ims.shape

torch.Size([6, 98, 98, 3])

In [ ]:
_, h, w, c = ims.shape

In [ ]:
(ims.reshape(2,-1, h, w, c).transpose(1,2).reshape(2, h, -1, c).max(0).values == reduce(ims, "(b1 b2) h w c -> h (b2 w) c", "max", b1=2)).all()

tensor(True)

In [ ]:
rearrange(ims, "b (h 1) w c -> b h 1 w c")

tensor([[[[[4, 2, 3],
           [0, 4, 2],
           [9, 0, 4],
           ...,
           [1, 9, 5],
           [6, 0, 2],
           [6, 3, 3]]],


         [[[7, 8, 9],
           [0, 9, 4],
           [7, 8, 8],
           ...,
           [5, 0, 8],
           [7, 7, 9],
           [7, 1, 8]]],


         [[[3, 1, 5],
           [2, 8, 3],
           [3, 7, 9],
           ...,
           [6, 2, 6],
           [7, 4, 9],
           [2, 9, 0]]],


         ...,


         [[[8, 4, 7],
           [7, 7, 5],
           [2, 2, 0],
           ...,
           [4, 5, 4],
           [5, 3, 3],
           [8, 0, 9]]],


         [[[2, 1, 0],
           [3, 0, 3],
           [8, 8, 6],
           ...,
           [5, 1, 3],
           [1, 0, 3],
           [3, 0, 7]]],


         [[[1, 3, 8],
           [9, 0, 9],
           [3, 9, 1],
           ...,
           [3, 2, 8],
           [1, 1, 9],
           [2, 1, 1]]]],



        [[[[0, 8, 2],
           [0, 5, 3],
           [6, 5, 7],
    

In [ ]:
ims = torch.randint(0,10,(2,2,4,4))

In [ ]:
ims

tensor([[[[1, 0, 5, 2],
          [1, 0, 7, 3],
          [3, 1, 6, 5],
          [3, 6, 7, 2]],

         [[1, 8, 0, 3],
          [4, 3, 6, 6],
          [2, 0, 9, 7],
          [3, 2, 9, 7]]],


        [[[4, 8, 3, 3],
          [1, 8, 4, 9],
          [4, 0, 2, 4],
          [6, 6, 9, 4]],

         [[9, 1, 2, 8],
          [3, 0, 0, 1],
          [5, 6, 9, 4],
          [9, 2, 0, 1]]]])

In [ ]:
rearrange(ims, "b c (h h1) (w w1) -> b c h h1 w w1", h1=2, w1=2)

tensor([[[[[[1, 0],
            [5, 2]],

           [[1, 0],
            [7, 3]]],


          [[[3, 1],
            [6, 5]],

           [[3, 6],
            [7, 2]]]],



         [[[[1, 8],
            [0, 3]],

           [[4, 3],
            [6, 6]]],


          [[[2, 0],
            [9, 7]],

           [[3, 2],
            [9, 7]]]]],




        [[[[[4, 8],
            [3, 3]],

           [[1, 8],
            [4, 9]]],


          [[[4, 0],
            [2, 4]],

           [[6, 6],
            [9, 4]]]],



         [[[[9, 1],
            [2, 8]],

           [[3, 0],
            [0, 1]]],


          [[[5, 6],
            [9, 4]],

           [[9, 2],
            [0, 1]]]]]])

In [ ]:
rearrange(ims, "b c (h h1) (w w1) -> b c h w h1 w1", h1=2, w1=2)

tensor([[[[[[1, 0],
            [1, 0]],

           [[5, 2],
            [7, 3]]],


          [[[3, 1],
            [3, 6]],

           [[6, 5],
            [7, 2]]]],



         [[[[1, 8],
            [4, 3]],

           [[0, 3],
            [6, 6]]],


          [[[2, 0],
            [3, 2]],

           [[9, 7],
            [9, 7]]]]],




        [[[[[4, 8],
            [1, 8]],

           [[3, 3],
            [4, 9]]],


          [[[4, 0],
            [6, 6]],

           [[2, 4],
            [9, 4]]]],



         [[[[9, 1],
            [3, 0]],

           [[2, 8],
            [0, 1]]],


          [[[5, 6],
            [9, 2]],

           [[9, 4],
            [0, 1]]]]]])

In [ ]:
images = torch.randn(64, 128, 128, 3) # (batch, height, width, channel)
dim_by = torch.linspace(start=0.0, end=1.0, steps=10)

In [ ]:
dim_by

tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])

In [ ]:
dim_value = rearrange(dim_by, "dim_value -> 1 dim_value 1 1 1")
images_rearr = rearrange(images, "b height width channel -> b 1 height width channel")
dimmed_images = images_rearr * dim_value

In [ ]:
(dimmed_images[:, -1, ...] == images).all()

tensor(True)

In [ ]:
channels_last = torch.randn(64, 4, 4, 3, dtype=torch.float64) # (batch, height, width, channel)
B = torch.randn(4*4, 4*4, dtype=torch.float64)

In [ ]:
## Rearrange an image tensor for mixing across all pixels
channels_last_flat = channels_last.view(-1, channels_last.size(1) * channels_last.size(2), channels_last.size(3))
channels_first_flat = channels_last_flat.transpose(1, 2)
channels_first_flat_transformed = channels_first_flat @ B.T
channels_last_flat_transformed = channels_first_flat_transformed.transpose(1, 2)
channels_last_transformed = channels_last_flat_transformed.view(*channels_last.shape)
channels_last_transformed.shape

torch.Size([64, 4, 4, 3])

In [ ]:
height = width = 4
## Rearrange replaces clunky torch view + transpose
channels_first = rearrange(channels_last, "batch height width channel -> batch channel (height width)")
channels_first_transformed = einsum(channels_first, B, "batch channel pixel_in, pixel_out pixel_in -> batch channel pixel_out")
channels_last_transformed3 = rearrange(channels_first_transformed,
                                       "batch channel (height width) -> batch height width channel",
                                       height=height, width=width)

In [ ]:
torch.allclose(channels_last_transformed, channels_last_transformed3, atol=1e-15)

True

In [ ]:
B.shape

torch.Size([1024, 1024])

In [ ]:
# Set a fixed random seed for reproducibility
torch.manual_seed(42)

# Fixed input tensor parameters
batch_size = 2
height = 4
width = 4
channels = 3
pixels = height * width

# Fixed input tensors
channels_last = torch.randn(batch_size, height, width, channels, dtype=torch.float64) # Use float64 for higher precision
B = torch.randn(pixels, pixels, dtype=torch.float64) # Use float64 for higher precision

# --- Torch approach ---
print("--- Running Torch Approach ---")
# 1. (batch, height, width, channel) -> (batch, H*W, channel)
channels_last_flat_torch = channels_last.view(
    batch_size, pixels, channels
)
print(f"channels_last_flat_torch shape: {channels_last_flat_torch.shape}")

# 2. (batch, H*W, channel) -> (batch, channel, H*W)
channels_first_flat_torch = channels_last_flat_torch.transpose(1, 2)
print(f"channels_first_flat_torch shape: {channels_first_flat_torch.shape}")

# 3. Apply transformation: (batch, channel, H*W_in) @ (H*W_in, H*W_out) -> (batch, channel, H*W_out)
# Note: B has shape (pixel_out, pixel_in). For matmul, we need (pixel_in, pixel_out)
# So, channels_first_flat_torch @ B.T is correct.
channels_first_transformed_torch = channels_first_flat_torch @ B.T
print(f"channels_first_transformed_torch shape: {channels_first_transformed_torch.shape}")

# 4. (batch, channel, H*W) -> (batch, H*W, channel)
channels_last_flat_transformed_torch = channels_first_transformed_torch.transpose(1, 2)
print(f"channels_last_flat_transformed_torch shape: {channels_last_flat_transformed_torch.shape}")

# 5. (batch, H*W, channel) -> (batch, height, width, channel)
channels_last_transformed_torch = channels_last_flat_transformed_torch.view(*channels_last.shape)
print(f"Final Torch output shape: {channels_last_transformed_torch.shape}")


# --- Einops approach ---
print("\n--- Running Einops Approach ---")
# 1. (batch, height, width, channel) -> (batch, channel, H*W)
channels_first_einops = rearrange(
    channels_last,
    "batch height width channel -> batch channel (height width)"
)
print(f"channels_first_einops shape: {channels_first_einops.shape}")

# 2. Apply transformation using einsum
# "batch channel pixel_in, pixel_out pixel_in -> batch channel pixel_out"
# This means: take 'pixel_in' from the first tensor, 'pixel_in' and 'pixel_out' from B.
# Contract 'pixel_in'. Result contains 'batch', 'channel', 'pixel_out'.
channels_first_transformed_einops = einsum(
    channels_first_einops, B,
    "batch channel pixel_in, pixel_out pixel_in -> batch channel pixel_out"
)
print(f"channels_first_transformed_einops shape: {channels_first_transformed_einops.shape}")

# 3. (batch, channel, H*W) -> (batch, height, width, channel)
channels_last_transformed_einops = rearrange(
    channels_first_transformed_einops,
    "batch channel (height width) -> batch height width channel",
    height=height, width=width
)
print(f"Final Einops output shape: {channels_last_transformed_einops.shape}")

# --- Comparison ---
# Using a higher tolerance (e.g., 1e-8 or 1e-9) might still be true
# since we used float64, but 1e-6 is generally safe for float32 as well.
are_same = torch.allclose(channels_last_transformed_torch, channels_last_transformed_einops, atol=1e-8)

print(f"\nAre the final results numerically identical (within tolerance of 1e-8)? {are_same}")

# Optional: Print a small portion to visually inspect differences if any
# if not are_same:
#     print("\nDifferences found:")
#     diff = torch.abs(channels_last_transformed_torch - channels_last_transformed_einops)
#     print(diff.max())
#     print(torch.where(diff > 1e-8)) # Show indices where difference is significant

--- Running Torch Approach ---
channels_last_flat_torch shape: torch.Size([2, 16, 3])
channels_first_flat_torch shape: torch.Size([2, 3, 16])
channels_first_transformed_torch shape: torch.Size([2, 3, 16])
channels_last_flat_transformed_torch shape: torch.Size([2, 16, 3])
Final Torch output shape: torch.Size([2, 4, 4, 3])

--- Running Einops Approach ---
channels_first_einops shape: torch.Size([2, 3, 16])
channels_first_transformed_einops shape: torch.Size([2, 3, 16])
Final Einops output shape: torch.Size([2, 4, 4, 3])

Are the final results numerically identical (within tolerance of 1e-8)? True


In [ ]:
torch.allclose(channels_last_transformed_torch, channels_last_transformed_einops, atol=1e-8)

True

In [74]:
import torch
from model import Embedding

ImportError: cannot import name 'Embedding' from 'model' (/scratch/joluseti/projects/cs336/assignment1-basics/lm/model.py)

In [2]:
d_in, d_out = 1024, 10
weights = torch.randn(d_out, d_in)

In [ ]:
linear = Linear(d_in, d_out, dtype=torch.float32)
state_dict = {"weight": weights, "bias"}
linear.load_state_dict(state_dict)
in_features = torch.randn(20, d_in)

RuntimeError: Error(s) in loading state_dict for Linear:
	Missing key(s) in state_dict: "bias". 

In [5]:
linear(in_features).shape

torch.Size([20, 10])

In [18]:
from torch.nn.modules import Linear
import os
os.environ["CUDA_VISIBLE_DEVICES"] ="0"

In [19]:
linear2 = Linear(d_in, d_out, dtype=torch.float32, device="cuda")

In [20]:
state_dict = {"weight": weights, "bias": torch.randn(10)}
linear2.load_state_dict(state_dict)

<All keys matched successfully>

In [22]:
linear2(in_features.to('cuda'))

tensor([[ 22.9281, -41.6347, -43.9585,  42.9228, -37.9388,  -9.5117, -34.7022,
         -23.3540,  34.0536,  -7.8398],
        [-25.4753,  -6.6604,  28.6280, -28.9219, -84.6622,  33.2643, -12.5889,
          -8.2625,   8.3681,  40.1283],
        [ 54.0170,  36.4230,   6.1427, -81.8050, -28.3833,  -8.0420,  21.9401,
         -30.1377,  68.2078, -17.1069],
        [ 22.8329,  27.6397,   0.8188, -19.0780, -46.8212,  54.9417, -27.8225,
          14.4176, -36.6985, -85.1762],
        [ -9.7101, -49.0083, -14.8771,  -3.9882,  14.3494,  -7.3470,  -5.5882,
          42.6207,  19.8132, -19.2995],
        [  7.7210, -36.2020,  10.9692,  -4.8491,  73.6474, -21.8623, -51.1098,
         -48.9651, -44.0815,  32.0942],
        [ -9.3539, -21.6876,  -3.5954,  -0.6935,  45.5540,  13.7897, -14.4886,
          17.5148,  31.1351,   5.5653],
        [-30.8055,   9.9373,  20.0790,  30.2204,  71.6259, -31.9943, -24.6933,
          37.3241,  39.0819,  54.9388],
        [ 35.8494,  10.9286,   9.5797,   2.2434,

In [43]:
embed = torch.randn(11,2)
embed

tensor([[ 0.7144,  1.2717],
        [ 0.2626, -2.1227],
        [-2.1616, -0.0843],
        [ 0.7263, -2.5967],
        [-0.9004,  0.3037],
        [-0.4742, -0.0326],
        [-0.1288, -0.7562],
        [-0.5627,  1.4750],
        [ 0.3628,  0.0655],
        [-1.5408, -2.1797],
        [ 0.6867, -1.1440]])

In [42]:
tokens = torch.randint(0, 11, (4, 2), dtype=torch.long).to("cuda")
tokens

tensor([[ 0,  6],
        [10,  9],
        [ 2,  5],
        [ 0,  5]], device='cuda:0')

In [44]:
embed[tokens]

RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

In [1]:
from einops import reduce
import torch

In [17]:
x = torch.randn(5, 10, 4, dtype=torch.bfloat16)
eps = 1e-5
d_model = x.shape[-1]

In [3]:
rms_x = (reduce(x**2, "b s d -> b s ()", "sum") / d_model) + eps

In [4]:
rms_x.shape

torch.Size([5, 10, 1])

In [23]:
rms_3 = (torch.square(x.to(torch.float32)).sum(-1)/d_model + eps).unsqueeze(-1)

In [9]:
rms_3.shape

torch.Size([5, 10, 1])

In [12]:
((x / rms_3) == x / rms_x).all()

tensor(True)

In [18]:
from model import RMSNorm
rms = RMSNorm(x.shape[-1])

In [19]:
res = rms(x)

In [24]:
res2 = x.to(torch.float32) / rms_3

In [ ]:
(x.to(torch.float32) / rms_x == res).all()

tensor(False)

In [1]:
d_model = 700
(8 * d_model // 3) + ((8 * d_model // 3) % 64)

1876

In [2]:
round(d_model / 24) * 64

1856

In [55]:
64 * 29 /d_model

2.6514285714285712

In [59]:
64 * 29

1856

In [48]:
8/3

2.6666666666666665

In [58]:
int(res) / 64

29.328125

In [26]:
res2[0].to(torch.bfloat16)

tensor([[-0.5898,  1.1016, -0.4473, -1.2266],
        [ 2.5469, -0.5312,  0.1475, -2.5469],
        [-0.1177,  0.6094,  1.4219,  0.3965],
        [-1.0234,  1.2656, -1.3906,  0.3711],
        [ 0.6367,  0.2773, -0.5352, -1.3906],
        [-0.4121, -0.6211,  0.2891,  0.8906],
        [ 2.2500, -0.1069, -1.9219,  2.6875],
        [-2.3906, -1.2188, -1.2266,  1.5547],
        [-0.8477, -0.9570, -1.2812, -0.1445],
        [-2.3906, -0.2148,  1.1406, -1.3672]], dtype=torch.bfloat16)

In [1]:
import torch

In [3]:
x = torch.arange(1, 5)

In [4]:
x

tensor([1, 2, 3, 4])

In [13]:
y = torch.stack([x,x], dim=-1).flatten()
y

tensor([1, 1, 2, 2, 3, 3, 4, 4])

In [11]:
res = 1/10**(2*y/8)

In [12]:
res

tensor([0.5623, 0.5623, 0.3162, 0.3162, 0.1778, 0.1778, 0.1000, 0.1000])

In [14]:
1/(10**(2/8))

0.5623413251903491

In [17]:
x = torch.arange(1,11).reshape(5,2)

In [74]:

x = x[0]

In [77]:
x.shape

torch.Size([5, 2])

In [80]:
x

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [65]:
from einops import repeat

In [84]:
z = x.repeat_interleave(2, dim=-1)

In [69]:
repeat(x, '... d -> ... (d r)', r=2)

tensor([[[ 1,  1,  2,  2],
         [ 3,  3,  4,  4],
         [ 5,  5,  6,  6],
         [ 7,  7,  8,  8],
         [ 9,  9, 10, 10]],

        [[ 1,  1,  2,  2],
         [ 3,  3,  4,  4],
         [ 5,  5,  6,  6],
         [ 7,  7,  8,  8],
         [ 9,  9, 10, 10]],

        [[ 1,  1,  2,  2],
         [ 3,  3,  4,  4],
         [ 5,  5,  6,  6],
         [ 7,  7,  8,  8],
         [ 9,  9, 10, 10]]])

In [27]:
t =torch.stack([x,x], dim=-1)

In [37]:
t

tensor([[[ 1,  1],
         [ 2,  2]],

        [[ 3,  3],
         [ 4,  4]],

        [[ 5,  5],
         [ 6,  6]],

        [[ 7,  7],
         [ 8,  8]],

        [[ 9,  9],
         [10, 10]]])

In [63]:
y = torch.flatten(t,start_dim=1)

In [64]:
y

tensor([[ 1,  1,  2,  2],
        [ 3,  3,  4,  4],
        [ 5,  5,  6,  6],
        [ 7,  7,  8,  8],
        [ 9,  9, 10, 10]])

In [62]:
t.squeeze(1)

tensor([[[ 1,  1],
         [ 2,  2]],

        [[ 3,  3],
         [ 4,  4]],

        [[ 5,  5],
         [ 6,  6]],

        [[ 7,  7],
         [ 8,  8]],

        [[ 9,  9],
         [10, 10]]])

In [85]:
z

tensor([[ 1,  1,  2,  2],
        [ 3,  3,  4,  4],
        [ 5,  5,  6,  6],
        [ 7,  7,  8,  8],
        [ 9,  9, 10, 10]])

In [93]:
q = torch.randint(0, 4, (10, 5, 10))

In [95]:
q

tensor([[[3, 1, 0, 2, 1, 0, 2, 1, 2, 1],
         [1, 0, 1, 3, 3, 0, 0, 3, 1, 3],
         [0, 3, 0, 1, 3, 3, 2, 2, 3, 3],
         [2, 2, 2, 1, 2, 0, 3, 2, 1, 3],
         [3, 3, 2, 0, 3, 3, 0, 2, 0, 1]],

        [[1, 0, 2, 0, 1, 2, 0, 1, 0, 0],
         [2, 3, 1, 1, 0, 2, 0, 0, 0, 3],
         [2, 2, 2, 1, 3, 0, 2, 1, 1, 3],
         [3, 1, 3, 2, 2, 1, 0, 1, 1, 2],
         [0, 3, 0, 2, 2, 1, 3, 0, 3, 2]],

        [[0, 1, 0, 2, 3, 0, 1, 3, 1, 3],
         [0, 0, 0, 3, 2, 2, 0, 2, 2, 2],
         [3, 2, 0, 0, 1, 3, 3, 2, 2, 1],
         [0, 1, 2, 2, 0, 0, 1, 3, 2, 0],
         [3, 3, 0, 3, 1, 2, 0, 2, 3, 1]],

        [[2, 0, 0, 0, 1, 2, 3, 3, 2, 2],
         [1, 1, 0, 3, 0, 3, 2, 0, 3, 3],
         [1, 2, 2, 1, 2, 2, 1, 3, 3, 0],
         [1, 0, 1, 2, 3, 3, 3, 0, 2, 0],
         [0, 2, 0, 1, 3, 1, 2, 0, 3, 1]],

        [[2, 3, 3, 0, 3, 0, 3, 2, 1, 0],
         [3, 1, 2, 0, 0, 0, 0, 0, 3, 0],
         [1, 1, 2, 2, 1, 2, 0, 1, 0, 0],
         [3, 3, 3, 2, 1, 0, 1, 3, 0, 0],
        

In [98]:
t = q.clone()

In [104]:
t[...,::2] = q[...,1::2] *-1
t[...,1::2] = q[...,::2]

In [105]:
t[0]

tensor([[-1,  3, -2,  0,  0,  1, -1,  2, -1,  2],
        [ 0,  1, -3,  1,  0,  3, -3,  0, -3,  1],
        [-3,  0, -1,  0, -3,  3, -2,  2, -3,  3],
        [-2,  2, -1,  2,  0,  2, -2,  3, -3,  1],
        [-3,  3,  0,  2, -3,  3, -2,  0, -1,  0]])

In [102]:
q[0]

tensor([[3, 1, 0, 2, 1, 0, 2, 1, 2, 1],
        [1, 0, 1, 3, 3, 0, 0, 3, 1, 3],
        [0, 3, 0, 1, 3, 3, 2, 2, 3, 3],
        [2, 2, 2, 1, 2, 0, 3, 2, 1, 3],
        [3, 3, 2, 0, 3, 3, 0, 2, 0, 1]])

In [89]:
z[q].repeat_interleave(repeats=2, dim=-1)

tensor([[[5, 5, 5, 5, 6, 6, 6, 6],
         [7, 7, 7, 7, 8, 8, 8, 8],
         [1, 1, 1, 1, 2, 2, 2, 2]],

        [[1, 1, 1, 1, 2, 2, 2, 2],
         [1, 1, 1, 1, 2, 2, 2, 2],
         [7, 7, 7, 7, 8, 8, 8, 8]],

        [[3, 3, 3, 3, 4, 4, 4, 4],
         [7, 7, 7, 7, 8, 8, 8, 8],
         [5, 5, 5, 5, 6, 6, 6, 6]],

        [[7, 7, 7, 7, 8, 8, 8, 8],
         [3, 3, 3, 3, 4, 4, 4, 4],
         [1, 1, 1, 1, 2, 2, 2, 2]],

        [[5, 5, 5, 5, 6, 6, 6, 6],
         [7, 7, 7, 7, 8, 8, 8, 8],
         [3, 3, 3, 3, 4, 4, 4, 4]]])

In [1]:
from model import ROPE
rope = ROPE(10000, 8, 100)

In [2]:
rope.cos_thetas.shape

torch.Size([100, 8])

In [3]:
import torch
x= torch.randn(10,50,8)
y = torch.randint(0, 50, (10, 50))

In [4]:
y[0][0]

tensor(29)

In [5]:
rope(x,y)[0][0]

tensor([ 1.3958,  0.1825, -0.2098, -0.2125,  0.6869,  0.4754,  0.5020, -0.7096])

In [6]:
x[0][0]

tensor([-1.3116, -0.5112, -0.2618, -0.1437,  0.7004,  0.4553,  0.4999, -0.7111])

In [7]:
rope.cos_thetas[29]

tensor([-0.9710, -0.9710,  0.9582,  0.9582,  0.9996,  0.9996,  1.0000,  1.0000])

In [8]:
y[0]

tensor([29, 31, 40, 49, 25, 15,  6, 31, 39, 43, 31,  2, 30, 45, 15, 13, 10, 44,
        43, 35, 13, 48,  6,  1, 49, 34, 31, 12, 24,  5, 37, 47, 20,  5, 26, 34,
        40, 49,  2, 44, 32, 27, 28, 35, 35, 33, 11, 13, 23,  1])

In [9]:
torch.cos(torch.tensor([29/10000**(2/8)]))

tensor([-0.9710])

In [13]:
import math


rot1 = math.cos(29/(10000**(2/8)))
rot2 = math.sin(29/10000**(2/8))

In [14]:
rot1

-0.9709581651495905

In [17]:
x[0][0][0] * rot1 + -x[0][0][1] * rot2

tensor(1.3958)